### ISSUE TITLE
Ajouter des tests unitaire sur les fonctions dans utils 25 min

### ISSUE THREAD

**Issue by keviant16** [keviant16/play-with-word-web#7]
- [ ] Suivre un guide sur les tests unitaires en JS
- [ ] Implementer une fonction de test pour la fonction compareStrIteration

**Comment by keviant16** [comment]
Cant run npm test run.
Error : 

`
'stencil' is not recognized as an internal or external command,
operable program or batch file.
[ERROR] Unable to find command: /react-router
[ERROR] Unable to find command: /core
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at StreamHandler.handle (C:\Users\kevin\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\@ionic\cli-framework-output\dist\logger.js:52:21)
    at Logger.log (C:\Users\kevin\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\@ionic\cli-framework-output\dist\logger.js:146:21)
    at Logger.rawmsg (C:\Users\kevin\AppData\Roaming\npm\node_modules\@ionic\cli\lib\utils\logger.js:13:14)
    at HelpCommand.run (C:\Users\kevin\AppData\Roaming\npm\node_modules\@ionic\cli\commands\help.js:53:26)
    at async Promise.all (index 0)
    at async HelpCommand.execute (C:\Users\kevin\AppData\Roaming\npm\node_modules\@ionic\cli\lib\command.js:81:9)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {     
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}


  ● Test suite failed to run

    SyntaxError: Invalid regular expression: /'node_modules\\(?!(@ionic\\react/: Unterminated group
        at new RegExp (<anonymous>)

former.js:924:29)      at SearchSource._getOrBuildDependencyResolver (node_modules/@jest/core/build/SearchSource.js:227:59)      at SearchSource.findRelatedTests (node_modules/@jest/core/build/SearchSource.js:288:43)      at SearchSource.findTestRelatedToChangedFiles (node_modules/@jest/core/build/SearchSource.js:377:17)      at SearchSource._getTestPaths (node_modules/@jest/core/build/SearchSource.js:386:19)`
